// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace ProcessOrder.DataService.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RenameOrderBase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameOrderBase));
        
        string IMigrationMetadata.Id
        {
            get { return "201602221747404_RenameOrderBase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
